/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID localhost.localdomain)
#  Generated on:      Thu Jun  3 13:10:06 2021
#  Design:            RCA_size128
#  Command:           saveNetlist RCA_size128.v
###############################################################
*/
module FA_0 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n1;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X1 FE_RC_141_0 (.A1(n5),
	.A2(n4),
	.B1(n1),
	.B2(n3),
	.ZN(c_out));
   XOR2_X1 U3 (.A(c_in),
	.B(n2),
	.Z(s));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U4 (.A(a),
	.ZN(n4));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XNOR2_X1 U6 (.A(a),
	.B(b),
	.ZN(n1));
   INV_X1 U7 (.A(n1),
	.ZN(n2));
endmodule

module FA_1 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   XNOR2_X1 U1 (.A(c_in),
	.B(n1),
	.ZN(s));
   INV_X1 U2 (.A(c_in),
	.ZN(n2));
   XOR2_X1 U3 (.A(n3),
	.B(b),
	.Z(n1));
   OAI22_X1 U4 (.A1(n2),
	.A2(n1),
	.B1(n3),
	.B2(n4),
	.ZN(c_out));
   INV_X1 U5 (.A(a),
	.ZN(n3));
   INV_X1 U6 (.A(b),
	.ZN(n4));
endmodule

module FA_2 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_68_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_137_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_68_0));
   OAI21_X4 FE_RC_136_0 (.A(FE_RN_68_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_3 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_67_0;
   wire net1558;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_135_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_67_0));
   OAI21_X4 FE_RC_134_0 (.A(FE_RN_67_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U1 (.A(n1),
	.ZN(net1558));
   INV_X1 U3 (.A(b),
	.ZN(n4));
   INV_X1 U4 (.A(a),
	.ZN(n3));
   XOR2_X1 U5 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U6 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U8 (.A(n2),
	.B(net1558),
	.ZN(s));
endmodule

module FA_4 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OAI22_X2 U1 (.A1(n2),
	.A2(n1),
	.B1(n3),
	.B2(n4),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_5 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_66_0;
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OR2_X1 FE_RC_133_0 (.A1(n4),
	.A2(n5),
	.ZN(FE_RN_66_0));
   OAI21_X4 FE_RC_132_0 (.A(FE_RN_66_0),
	.B1(n3),
	.B2(n2),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_6 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OAI22_X2 U1 (.A1(n2),
	.A2(n1),
	.B1(n3),
	.B2(n4),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_7 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_63_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_127_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_63_0));
   OAI21_X4 FE_RC_126_0 (.A(FE_RN_63_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_8 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_65_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_131_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_65_0));
   OAI21_X4 FE_RC_130_0 (.A(FE_RN_65_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_9 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_64_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_129_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_64_0));
   OAI21_X4 FE_RC_128_0 (.A(FE_RN_64_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_10 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_61_0;
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OR2_X1 FE_RC_123_0 (.A1(n4),
	.A2(n5),
	.ZN(FE_RN_61_0));
   OAI21_X4 FE_RC_122_0 (.A(FE_RN_61_0),
	.B1(n3),
	.B2(n2),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_11 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OAI22_X2 U1 (.A1(n2),
	.A2(n1),
	.B1(n3),
	.B2(n4),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_12 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_60_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_121_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_60_0));
   OAI21_X4 FE_RC_120_0 (.A(FE_RN_60_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_13 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_59_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_119_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_59_0));
   OAI21_X4 FE_RC_118_0 (.A(FE_RN_59_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_14 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_56_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_113_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_56_0));
   OAI21_X4 FE_RC_112_0 (.A(FE_RN_56_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_15 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_55_0;
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OR2_X1 FE_RC_111_0 (.A1(n4),
	.A2(n5),
	.ZN(FE_RN_55_0));
   OAI21_X4 FE_RC_110_0 (.A(FE_RN_55_0),
	.B1(n3),
	.B2(n2),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_16 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OAI22_X2 U1 (.A1(n2),
	.A2(n1),
	.B1(n3),
	.B2(n4),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_17 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_53_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_107_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_53_0));
   OAI21_X4 FE_RC_106_0 (.A(FE_RN_53_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_18 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_54_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_109_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_54_0));
   OAI21_X4 FE_RC_108_0 (.A(FE_RN_54_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_19 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_51_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_103_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_51_0));
   OAI21_X4 FE_RC_102_0 (.A(FE_RN_51_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_20 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_52_0;
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OR2_X1 FE_RC_105_0 (.A1(n4),
	.A2(n5),
	.ZN(FE_RN_52_0));
   OAI21_X4 FE_RC_104_0 (.A(FE_RN_52_0),
	.B1(n3),
	.B2(n2),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_21 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OAI22_X2 U1 (.A1(n2),
	.A2(n1),
	.B1(n3),
	.B2(n4),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_22 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_49_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_99_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_49_0));
   OAI21_X4 FE_RC_98_0 (.A(FE_RN_49_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_23 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_47_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_95_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_47_0));
   OAI21_X4 FE_RC_94_0 (.A(FE_RN_47_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_24 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_50_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_101_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_50_0));
   OAI21_X4 FE_RC_100_0 (.A(FE_RN_50_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_25 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_42_0;
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OR2_X1 FE_RC_85_0 (.A1(n4),
	.A2(n5),
	.ZN(FE_RN_42_0));
   OAI21_X4 FE_RC_84_0 (.A(FE_RN_42_0),
	.B1(n3),
	.B2(n2),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_26 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OAI22_X2 U1 (.A1(n2),
	.A2(n1),
	.B1(n3),
	.B2(n4),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_27 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_3_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_7_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_3_0));
   OAI21_X4 FE_RC_6_0 (.A(FE_RN_3_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_28 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_45_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_91_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_45_0));
   OAI21_X4 FE_RC_90_0 (.A(FE_RN_45_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_29 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_30_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_61_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_30_0));
   OAI21_X4 FE_RC_60_0 (.A(FE_RN_30_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_30 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_6_0;
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OR2_X1 FE_RC_13_0 (.A1(n4),
	.A2(n5),
	.ZN(FE_RN_6_0));
   OAI21_X4 FE_RC_12_0 (.A(FE_RN_6_0),
	.B1(n3),
	.B2(n2),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_31 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OAI22_X2 U1 (.A1(n2),
	.A2(n1),
	.B1(n3),
	.B2(n4),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_32 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_34_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_69_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_34_0));
   OAI21_X4 FE_RC_68_0 (.A(FE_RN_34_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_33 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_11_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_23_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_11_0));
   OAI21_X4 FE_RC_22_0 (.A(FE_RN_11_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_34 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_21_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_43_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_21_0));
   OAI21_X4 FE_RC_42_0 (.A(FE_RN_21_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_35 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_7_0;
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OR2_X1 FE_RC_15_0 (.A1(n4),
	.A2(n5),
	.ZN(FE_RN_7_0));
   OAI21_X4 FE_RC_14_0 (.A(FE_RN_7_0),
	.B1(n3),
	.B2(n2),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_36 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OAI22_X2 U1 (.A1(n2),
	.A2(n1),
	.B1(n3),
	.B2(n4),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_37 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_9_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_19_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_9_0));
   OAI21_X4 FE_RC_18_0 (.A(FE_RN_9_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_38 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_18_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_37_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_18_0));
   OAI21_X4 FE_RC_36_0 (.A(FE_RN_18_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_39 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_27_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_55_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_27_0));
   OAI21_X4 FE_RC_54_0 (.A(FE_RN_27_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_40 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_19_0;
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OR2_X1 FE_RC_39_0 (.A1(n4),
	.A2(n5),
	.ZN(FE_RN_19_0));
   OAI21_X4 FE_RC_38_0 (.A(FE_RN_19_0),
	.B1(n3),
	.B2(n2),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_41 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OAI22_X2 U1 (.A1(n2),
	.A2(n1),
	.B1(n3),
	.B2(n4),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_42 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_22_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_45_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_22_0));
   OAI21_X4 FE_RC_44_0 (.A(FE_RN_22_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_43 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_44_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_89_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_44_0));
   OAI21_X4 FE_RC_88_0 (.A(FE_RN_44_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_44 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_0_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_1_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_0_0));
   OAI21_X4 FE_RC_0_0 (.A(FE_RN_0_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_45 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_23_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_47_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_23_0));
   OAI21_X4 FE_RC_46_0 (.A(FE_RN_23_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_46 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_31_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_63_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_31_0));
   OAI21_X4 FE_RC_62_0 (.A(FE_RN_31_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_47 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_8_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_17_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_8_0));
   OAI21_X4 FE_RC_16_0 (.A(FE_RN_8_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_48 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_5_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_11_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_5_0));
   OAI21_X4 FE_RC_10_0 (.A(FE_RN_5_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_49 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_24_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_49_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_24_0));
   OAI21_X4 FE_RC_48_0 (.A(FE_RN_24_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_50 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_32_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_65_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_32_0));
   OAI21_X4 FE_RC_64_0 (.A(FE_RN_32_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_51 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_33_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_67_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_33_0));
   OAI21_X4 FE_RC_66_0 (.A(FE_RN_33_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_52 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_39_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_79_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_39_0));
   OAI21_X4 FE_RC_78_0 (.A(FE_RN_39_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_53 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_15_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_31_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_15_0));
   OAI21_X4 FE_RC_30_0 (.A(FE_RN_15_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_54 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_28_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_57_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_28_0));
   OAI21_X4 FE_RC_56_0 (.A(FE_RN_28_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_55 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_17_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_35_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_17_0));
   OAI21_X4 FE_RC_34_0 (.A(FE_RN_17_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_56 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_20_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_41_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_20_0));
   OAI21_X4 FE_RC_40_0 (.A(FE_RN_20_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_57 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_43_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_87_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_43_0));
   OAI21_X4 FE_RC_86_0 (.A(FE_RN_43_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_58 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_29_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_59_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_29_0));
   OAI21_X4 FE_RC_58_0 (.A(FE_RN_29_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_59 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_4_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_9_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_4_0));
   OAI21_X4 FE_RC_8_0 (.A(FE_RN_4_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_60 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_35_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_71_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_35_0));
   OAI21_X4 FE_RC_70_0 (.A(FE_RN_35_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_61 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_25_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_51_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_25_0));
   OAI21_X4 FE_RC_50_0 (.A(FE_RN_25_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_62 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_14_0;
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OR2_X1 FE_RC_29_0 (.A1(n4),
	.A2(n5),
	.ZN(FE_RN_14_0));
   OAI21_X4 FE_RC_28_0 (.A(FE_RN_14_0),
	.B1(n3),
	.B2(n2),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_63 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OAI22_X2 U1 (.A1(n2),
	.A2(n1),
	.B1(n3),
	.B2(n4),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_64 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_40_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_81_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_40_0));
   OAI21_X4 FE_RC_80_0 (.A(FE_RN_40_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_65 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_37_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_75_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_37_0));
   OAI21_X4 FE_RC_74_0 (.A(FE_RN_37_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_66 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_36_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_73_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_36_0));
   OAI21_X4 FE_RC_72_0 (.A(FE_RN_36_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_67 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_12_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_25_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_12_0));
   OAI21_X4 FE_RC_24_0 (.A(FE_RN_12_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_68 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_41_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_83_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_41_0));
   OAI21_X4 FE_RC_82_0 (.A(FE_RN_41_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_69 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_26_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_53_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_26_0));
   OAI21_X4 FE_RC_52_0 (.A(FE_RN_26_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_70 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_16_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_33_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_16_0));
   OAI21_X4 FE_RC_32_0 (.A(FE_RN_16_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_71 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_13_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_27_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_13_0));
   OAI21_X4 FE_RC_26_0 (.A(FE_RN_13_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_72 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_10_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_21_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_10_0));
   OAI21_X4 FE_RC_20_0 (.A(FE_RN_10_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_73 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_1_0;
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OR2_X1 FE_RC_3_0 (.A1(n4),
	.A2(n5),
	.ZN(FE_RN_1_0));
   OAI21_X4 FE_RC_2_0 (.A(FE_RN_1_0),
	.B1(n3),
	.B2(n2),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_74 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_75 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X4 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_76 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X4 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_77 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_78 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X4 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_79 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_80 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X4 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_81 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_82 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_83 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_84 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X4 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_85 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OAI22_X2 U1 (.A1(n2),
	.A2(n1),
	.B1(n3),
	.B2(n4),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_86 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_2_0;
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OR2_X1 FE_RC_5_0 (.A1(n4),
	.A2(n5),
	.ZN(FE_RN_2_0));
   OAI21_X4 FE_RC_4_0 (.A(FE_RN_2_0),
	.B1(n3),
	.B2(n2),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_87 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_88 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X4 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_89 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OAI22_X2 U1 (.A1(n2),
	.A2(n1),
	.B1(n3),
	.B2(n4),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_90 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_46_0;
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OR2_X1 FE_RC_93_0 (.A1(n4),
	.A2(n5),
	.ZN(FE_RN_46_0));
   OAI21_X4 FE_RC_92_0 (.A(FE_RN_46_0),
	.B1(n3),
	.B2(n2),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_91 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_92 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_93 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X4 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_94 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_95 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X4 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_96 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X4 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_97 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_98 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OAI22_X2 U1 (.A1(n2),
	.A2(n1),
	.B1(n3),
	.B2(n4),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_99 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_38_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_77_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_38_0));
   OAI21_X4 FE_RC_76_0 (.A(FE_RN_38_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X2 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_100 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_48_0;
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OR2_X1 FE_RC_97_0 (.A1(n4),
	.A2(n5),
	.ZN(FE_RN_48_0));
   OAI21_X4 FE_RC_96_0 (.A(FE_RN_48_0),
	.B1(n3),
	.B2(n2),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_101 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_102 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_103 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_104 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OAI22_X2 U1 (.A1(n2),
	.A2(n1),
	.B1(n3),
	.B2(n4),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_105 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_58_0;
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OR2_X1 FE_RC_117_0 (.A1(n3),
	.A2(n4),
	.ZN(FE_RN_58_0));
   OAI21_X4 FE_RC_116_0 (.A(FE_RN_58_0),
	.B1(n2),
	.B2(n1),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_106 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_57_0;
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OR2_X1 FE_RC_115_0 (.A1(n4),
	.A2(n5),
	.ZN(FE_RN_57_0));
   OAI21_X4 FE_RC_114_0 (.A(FE_RN_57_0),
	.B1(n3),
	.B2(n2),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_107 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OAI22_X2 U1 (.A1(n2),
	.A2(n1),
	.B1(n3),
	.B2(n4),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_108 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_62_0;
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OR2_X1 FE_RC_125_0 (.A1(n4),
	.A2(n5),
	.ZN(FE_RN_62_0));
   OAI21_X4 FE_RC_124_0 (.A(FE_RN_62_0),
	.B1(n3),
	.B2(n2),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X2 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_109 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_110 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_111 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_112 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_113 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_114 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;

   OAI22_X2 U1 (.A1(n2),
	.A2(n1),
	.B1(n3),
	.B2(n4),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n4));
   INV_X1 U3 (.A(a),
	.ZN(n3));
   XOR2_X1 U4 (.A(n3),
	.B(b),
	.Z(n1));
   INV_X1 U5 (.A(c_in),
	.ZN(n2));
   XNOR2_X1 U7 (.A(c_in),
	.B(n1),
	.ZN(s));
endmodule

module FA_115 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_69_0;
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OR2_X1 FE_RC_139_0 (.A1(n4),
	.A2(n5),
	.ZN(FE_RN_69_0));
   OAI21_X2 FE_RC_138_0 (.A(FE_RN_69_0),
	.B1(n3),
	.B2(n2),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_116 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_117 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_118 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_119 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_120 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_121 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X2 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_122 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X1 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_123 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X1 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_124 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X1 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_125 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X1 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_126 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   OAI22_X1 U1 (.A1(n3),
	.A2(n2),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   XOR2_X1 U4 (.A(n4),
	.B(b),
	.Z(n2));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module FA_127 (
	a, 
	b, 
	c_in, 
	c_out, 
	s);
   input a;
   input b;
   input c_in;
   output c_out;
   output s;

   // Internal wires
   wire FE_RN_73_0;
   wire FE_RN_71_0;
   wire FE_RN_70_0;
   wire n2;
   wire n3;
   wire n4;
   wire n5;

   INV_X1 FE_RC_146_0 (.A(n4),
	.ZN(FE_RN_70_0));
   NAND2_X1 FE_RC_145_0 (.A1(FE_RN_70_0),
	.A2(b),
	.ZN(FE_RN_71_0));
   NAND2_X1 FE_RC_143_0 (.A1(n4),
	.A2(n5),
	.ZN(FE_RN_73_0));
   NAND2_X1 FE_RC_142_0 (.A1(FE_RN_73_0),
	.A2(FE_RN_71_0),
	.ZN(n2));
   OAI22_X1 FE_RC_140_0 (.A1(n2),
	.A2(n3),
	.B1(n4),
	.B2(n5),
	.ZN(c_out));
   INV_X1 U2 (.A(b),
	.ZN(n5));
   INV_X1 U3 (.A(a),
	.ZN(n4));
   INV_X1 U5 (.A(c_in),
	.ZN(n3));
   XOR2_X1 U7 (.A(n3),
	.B(n2),
	.Z(s));
endmodule

module RCA_size128 (
	a, 
	b, 
	c_out, 
	sum);
   input [127:0] a;
   input [127:0] b;
   output c_out;
   output [127:0] sum;

   // Internal wires
   wire [127:1] temp;

   FA_0 fa_i_0 (.a(a[0]),
	.b(b[0]),
	.c_in(1'b0),
	.c_out(temp[1]),
	.s(sum[0]));
   FA_127 fa_i_1 (.a(a[1]),
	.b(b[1]),
	.c_in(temp[1]),
	.c_out(temp[2]),
	.s(sum[1]));
   FA_126 fa_i_2 (.a(a[2]),
	.b(b[2]),
	.c_in(temp[2]),
	.c_out(temp[3]),
	.s(sum[2]));
   FA_125 fa_i_3 (.a(a[3]),
	.b(b[3]),
	.c_in(temp[3]),
	.c_out(temp[4]),
	.s(sum[3]));
   FA_124 fa_i_4 (.a(a[4]),
	.b(b[4]),
	.c_in(temp[4]),
	.c_out(temp[5]),
	.s(sum[4]));
   FA_123 fa_i_5 (.a(a[5]),
	.b(b[5]),
	.c_in(temp[5]),
	.c_out(temp[6]),
	.s(sum[5]));
   FA_122 fa_i_6 (.a(a[6]),
	.b(b[6]),
	.c_in(temp[6]),
	.c_out(temp[7]),
	.s(sum[6]));
   FA_121 fa_i_7 (.a(a[7]),
	.b(b[7]),
	.c_in(temp[7]),
	.c_out(temp[8]),
	.s(sum[7]));
   FA_120 fa_i_8 (.a(a[8]),
	.b(b[8]),
	.c_in(temp[8]),
	.c_out(temp[9]),
	.s(sum[8]));
   FA_119 fa_i_9 (.a(a[9]),
	.b(b[9]),
	.c_in(temp[9]),
	.c_out(temp[10]),
	.s(sum[9]));
   FA_118 fa_i_10 (.a(a[10]),
	.b(b[10]),
	.c_in(temp[10]),
	.c_out(temp[11]),
	.s(sum[10]));
   FA_117 fa_i_11 (.a(a[11]),
	.b(b[11]),
	.c_in(temp[11]),
	.c_out(temp[12]),
	.s(sum[11]));
   FA_116 fa_i_12 (.a(a[12]),
	.b(b[12]),
	.c_in(temp[12]),
	.c_out(temp[13]),
	.s(sum[12]));
   FA_115 fa_i_13 (.a(a[13]),
	.b(b[13]),
	.c_in(temp[13]),
	.c_out(temp[14]),
	.s(sum[13]));
   FA_114 fa_i_14 (.a(a[14]),
	.b(b[14]),
	.c_in(temp[14]),
	.c_out(temp[15]),
	.s(sum[14]));
   FA_113 fa_i_15 (.a(a[15]),
	.b(b[15]),
	.c_in(temp[15]),
	.c_out(temp[16]),
	.s(sum[15]));
   FA_112 fa_i_16 (.a(a[16]),
	.b(b[16]),
	.c_in(temp[16]),
	.c_out(temp[17]),
	.s(sum[16]));
   FA_111 fa_i_17 (.a(a[17]),
	.b(b[17]),
	.c_in(temp[17]),
	.c_out(temp[18]),
	.s(sum[17]));
   FA_110 fa_i_18 (.a(a[18]),
	.b(b[18]),
	.c_in(temp[18]),
	.c_out(temp[19]),
	.s(sum[18]));
   FA_109 fa_i_19 (.a(a[19]),
	.b(b[19]),
	.c_in(temp[19]),
	.c_out(temp[20]),
	.s(sum[19]));
   FA_108 fa_i_20 (.a(a[20]),
	.b(b[20]),
	.c_in(temp[20]),
	.c_out(temp[21]),
	.s(sum[20]));
   FA_107 fa_i_21 (.a(a[21]),
	.b(b[21]),
	.c_in(temp[21]),
	.c_out(temp[22]),
	.s(sum[21]));
   FA_106 fa_i_22 (.a(a[22]),
	.b(b[22]),
	.c_in(temp[22]),
	.c_out(temp[23]),
	.s(sum[22]));
   FA_105 fa_i_23 (.a(a[23]),
	.b(b[23]),
	.c_in(temp[23]),
	.c_out(temp[24]),
	.s(sum[23]));
   FA_104 fa_i_24 (.a(a[24]),
	.b(b[24]),
	.c_in(temp[24]),
	.c_out(temp[25]),
	.s(sum[24]));
   FA_103 fa_i_25 (.a(a[25]),
	.b(b[25]),
	.c_in(temp[25]),
	.c_out(temp[26]),
	.s(sum[25]));
   FA_102 fa_i_26 (.a(a[26]),
	.b(b[26]),
	.c_in(temp[26]),
	.c_out(temp[27]),
	.s(sum[26]));
   FA_101 fa_i_27 (.a(a[27]),
	.b(b[27]),
	.c_in(temp[27]),
	.c_out(temp[28]),
	.s(sum[27]));
   FA_100 fa_i_28 (.a(a[28]),
	.b(b[28]),
	.c_in(temp[28]),
	.c_out(temp[29]),
	.s(sum[28]));
   FA_99 fa_i_29 (.a(a[29]),
	.b(b[29]),
	.c_in(temp[29]),
	.c_out(temp[30]),
	.s(sum[29]));
   FA_98 fa_i_30 (.a(a[30]),
	.b(b[30]),
	.c_in(temp[30]),
	.c_out(temp[31]),
	.s(sum[30]));
   FA_97 fa_i_31 (.a(a[31]),
	.b(b[31]),
	.c_in(temp[31]),
	.c_out(temp[32]),
	.s(sum[31]));
   FA_96 fa_i_32 (.a(a[32]),
	.b(b[32]),
	.c_in(temp[32]),
	.c_out(temp[33]),
	.s(sum[32]));
   FA_95 fa_i_33 (.a(a[33]),
	.b(b[33]),
	.c_in(temp[33]),
	.c_out(temp[34]),
	.s(sum[33]));
   FA_94 fa_i_34 (.a(a[34]),
	.b(b[34]),
	.c_in(temp[34]),
	.c_out(temp[35]),
	.s(sum[34]));
   FA_93 fa_i_35 (.a(a[35]),
	.b(b[35]),
	.c_in(temp[35]),
	.c_out(temp[36]),
	.s(sum[35]));
   FA_92 fa_i_36 (.a(a[36]),
	.b(b[36]),
	.c_in(temp[36]),
	.c_out(temp[37]),
	.s(sum[36]));
   FA_91 fa_i_37 (.a(a[37]),
	.b(b[37]),
	.c_in(temp[37]),
	.c_out(temp[38]),
	.s(sum[37]));
   FA_90 fa_i_38 (.a(a[38]),
	.b(b[38]),
	.c_in(temp[38]),
	.c_out(temp[39]),
	.s(sum[38]));
   FA_89 fa_i_39 (.a(a[39]),
	.b(b[39]),
	.c_in(temp[39]),
	.c_out(temp[40]),
	.s(sum[39]));
   FA_88 fa_i_40 (.a(a[40]),
	.b(b[40]),
	.c_in(temp[40]),
	.c_out(temp[41]),
	.s(sum[40]));
   FA_87 fa_i_41 (.a(a[41]),
	.b(b[41]),
	.c_in(temp[41]),
	.c_out(temp[42]),
	.s(sum[41]));
   FA_86 fa_i_42 (.a(a[42]),
	.b(b[42]),
	.c_in(temp[42]),
	.c_out(temp[43]),
	.s(sum[42]));
   FA_85 fa_i_43 (.a(a[43]),
	.b(b[43]),
	.c_in(temp[43]),
	.c_out(temp[44]),
	.s(sum[43]));
   FA_84 fa_i_44 (.a(a[44]),
	.b(b[44]),
	.c_in(temp[44]),
	.c_out(temp[45]),
	.s(sum[44]));
   FA_83 fa_i_45 (.a(a[45]),
	.b(b[45]),
	.c_in(temp[45]),
	.c_out(temp[46]),
	.s(sum[45]));
   FA_82 fa_i_46 (.a(a[46]),
	.b(b[46]),
	.c_in(temp[46]),
	.c_out(temp[47]),
	.s(sum[46]));
   FA_81 fa_i_47 (.a(a[47]),
	.b(b[47]),
	.c_in(temp[47]),
	.c_out(temp[48]),
	.s(sum[47]));
   FA_80 fa_i_48 (.a(a[48]),
	.b(b[48]),
	.c_in(temp[48]),
	.c_out(temp[49]),
	.s(sum[48]));
   FA_79 fa_i_49 (.a(a[49]),
	.b(b[49]),
	.c_in(temp[49]),
	.c_out(temp[50]),
	.s(sum[49]));
   FA_78 fa_i_50 (.a(a[50]),
	.b(b[50]),
	.c_in(temp[50]),
	.c_out(temp[51]),
	.s(sum[50]));
   FA_77 fa_i_51 (.a(a[51]),
	.b(b[51]),
	.c_in(temp[51]),
	.c_out(temp[52]),
	.s(sum[51]));
   FA_76 fa_i_52 (.a(a[52]),
	.b(b[52]),
	.c_in(temp[52]),
	.c_out(temp[53]),
	.s(sum[52]));
   FA_75 fa_i_53 (.a(a[53]),
	.b(b[53]),
	.c_in(temp[53]),
	.c_out(temp[54]),
	.s(sum[53]));
   FA_74 fa_i_54 (.a(a[54]),
	.b(b[54]),
	.c_in(temp[54]),
	.c_out(temp[55]),
	.s(sum[54]));
   FA_73 fa_i_55 (.a(a[55]),
	.b(b[55]),
	.c_in(temp[55]),
	.c_out(temp[56]),
	.s(sum[55]));
   FA_72 fa_i_56 (.a(a[56]),
	.b(b[56]),
	.c_in(temp[56]),
	.c_out(temp[57]),
	.s(sum[56]));
   FA_71 fa_i_57 (.a(a[57]),
	.b(b[57]),
	.c_in(temp[57]),
	.c_out(temp[58]),
	.s(sum[57]));
   FA_70 fa_i_58 (.a(a[58]),
	.b(b[58]),
	.c_in(temp[58]),
	.c_out(temp[59]),
	.s(sum[58]));
   FA_69 fa_i_59 (.a(a[59]),
	.b(b[59]),
	.c_in(temp[59]),
	.c_out(temp[60]),
	.s(sum[59]));
   FA_68 fa_i_60 (.a(a[60]),
	.b(b[60]),
	.c_in(temp[60]),
	.c_out(temp[61]),
	.s(sum[60]));
   FA_67 fa_i_61 (.a(a[61]),
	.b(b[61]),
	.c_in(temp[61]),
	.c_out(temp[62]),
	.s(sum[61]));
   FA_66 fa_i_62 (.a(a[62]),
	.b(b[62]),
	.c_in(temp[62]),
	.c_out(temp[63]),
	.s(sum[62]));
   FA_65 fa_i_63 (.a(a[63]),
	.b(b[63]),
	.c_in(temp[63]),
	.c_out(temp[64]),
	.s(sum[63]));
   FA_64 fa_i_64 (.a(a[64]),
	.b(b[64]),
	.c_in(temp[64]),
	.c_out(temp[65]),
	.s(sum[64]));
   FA_63 fa_i_65 (.a(a[65]),
	.b(b[65]),
	.c_in(temp[65]),
	.c_out(temp[66]),
	.s(sum[65]));
   FA_62 fa_i_66 (.a(a[66]),
	.b(b[66]),
	.c_in(temp[66]),
	.c_out(temp[67]),
	.s(sum[66]));
   FA_61 fa_i_67 (.a(a[67]),
	.b(b[67]),
	.c_in(temp[67]),
	.c_out(temp[68]),
	.s(sum[67]));
   FA_60 fa_i_68 (.a(a[68]),
	.b(b[68]),
	.c_in(temp[68]),
	.c_out(temp[69]),
	.s(sum[68]));
   FA_59 fa_i_69 (.a(a[69]),
	.b(b[69]),
	.c_in(temp[69]),
	.c_out(temp[70]),
	.s(sum[69]));
   FA_58 fa_i_70 (.a(a[70]),
	.b(b[70]),
	.c_in(temp[70]),
	.c_out(temp[71]),
	.s(sum[70]));
   FA_57 fa_i_71 (.a(a[71]),
	.b(b[71]),
	.c_in(temp[71]),
	.c_out(temp[72]),
	.s(sum[71]));
   FA_56 fa_i_72 (.a(a[72]),
	.b(b[72]),
	.c_in(temp[72]),
	.c_out(temp[73]),
	.s(sum[72]));
   FA_55 fa_i_73 (.a(a[73]),
	.b(b[73]),
	.c_in(temp[73]),
	.c_out(temp[74]),
	.s(sum[73]));
   FA_54 fa_i_74 (.a(a[74]),
	.b(b[74]),
	.c_in(temp[74]),
	.c_out(temp[75]),
	.s(sum[74]));
   FA_53 fa_i_75 (.a(a[75]),
	.b(b[75]),
	.c_in(temp[75]),
	.c_out(temp[76]),
	.s(sum[75]));
   FA_52 fa_i_76 (.a(a[76]),
	.b(b[76]),
	.c_in(temp[76]),
	.c_out(temp[77]),
	.s(sum[76]));
   FA_51 fa_i_77 (.a(a[77]),
	.b(b[77]),
	.c_in(temp[77]),
	.c_out(temp[78]),
	.s(sum[77]));
   FA_50 fa_i_78 (.a(a[78]),
	.b(b[78]),
	.c_in(temp[78]),
	.c_out(temp[79]),
	.s(sum[78]));
   FA_49 fa_i_79 (.a(a[79]),
	.b(b[79]),
	.c_in(temp[79]),
	.c_out(temp[80]),
	.s(sum[79]));
   FA_48 fa_i_80 (.a(a[80]),
	.b(b[80]),
	.c_in(temp[80]),
	.c_out(temp[81]),
	.s(sum[80]));
   FA_47 fa_i_81 (.a(a[81]),
	.b(b[81]),
	.c_in(temp[81]),
	.c_out(temp[82]),
	.s(sum[81]));
   FA_46 fa_i_82 (.a(a[82]),
	.b(b[82]),
	.c_in(temp[82]),
	.c_out(temp[83]),
	.s(sum[82]));
   FA_45 fa_i_83 (.a(a[83]),
	.b(b[83]),
	.c_in(temp[83]),
	.c_out(temp[84]),
	.s(sum[83]));
   FA_44 fa_i_84 (.a(a[84]),
	.b(b[84]),
	.c_in(temp[84]),
	.c_out(temp[85]),
	.s(sum[84]));
   FA_43 fa_i_85 (.a(a[85]),
	.b(b[85]),
	.c_in(temp[85]),
	.c_out(temp[86]),
	.s(sum[85]));
   FA_42 fa_i_86 (.a(a[86]),
	.b(b[86]),
	.c_in(temp[86]),
	.c_out(temp[87]),
	.s(sum[86]));
   FA_41 fa_i_87 (.a(a[87]),
	.b(b[87]),
	.c_in(temp[87]),
	.c_out(temp[88]),
	.s(sum[87]));
   FA_40 fa_i_88 (.a(a[88]),
	.b(b[88]),
	.c_in(temp[88]),
	.c_out(temp[89]),
	.s(sum[88]));
   FA_39 fa_i_89 (.a(a[89]),
	.b(b[89]),
	.c_in(temp[89]),
	.c_out(temp[90]),
	.s(sum[89]));
   FA_38 fa_i_90 (.a(a[90]),
	.b(b[90]),
	.c_in(temp[90]),
	.c_out(temp[91]),
	.s(sum[90]));
   FA_37 fa_i_91 (.a(a[91]),
	.b(b[91]),
	.c_in(temp[91]),
	.c_out(temp[92]),
	.s(sum[91]));
   FA_36 fa_i_92 (.a(a[92]),
	.b(b[92]),
	.c_in(temp[92]),
	.c_out(temp[93]),
	.s(sum[92]));
   FA_35 fa_i_93 (.a(a[93]),
	.b(b[93]),
	.c_in(temp[93]),
	.c_out(temp[94]),
	.s(sum[93]));
   FA_34 fa_i_94 (.a(a[94]),
	.b(b[94]),
	.c_in(temp[94]),
	.c_out(temp[95]),
	.s(sum[94]));
   FA_33 fa_i_95 (.a(a[95]),
	.b(b[95]),
	.c_in(temp[95]),
	.c_out(temp[96]),
	.s(sum[95]));
   FA_32 fa_i_96 (.a(a[96]),
	.b(b[96]),
	.c_in(temp[96]),
	.c_out(temp[97]),
	.s(sum[96]));
   FA_31 fa_i_97 (.a(a[97]),
	.b(b[97]),
	.c_in(temp[97]),
	.c_out(temp[98]),
	.s(sum[97]));
   FA_30 fa_i_98 (.a(a[98]),
	.b(b[98]),
	.c_in(temp[98]),
	.c_out(temp[99]),
	.s(sum[98]));
   FA_29 fa_i_99 (.a(a[99]),
	.b(b[99]),
	.c_in(temp[99]),
	.c_out(temp[100]),
	.s(sum[99]));
   FA_28 fa_i_100 (.a(a[100]),
	.b(b[100]),
	.c_in(temp[100]),
	.c_out(temp[101]),
	.s(sum[100]));
   FA_27 fa_i_101 (.a(a[101]),
	.b(b[101]),
	.c_in(temp[101]),
	.c_out(temp[102]),
	.s(sum[101]));
   FA_26 fa_i_102 (.a(a[102]),
	.b(b[102]),
	.c_in(temp[102]),
	.c_out(temp[103]),
	.s(sum[102]));
   FA_25 fa_i_103 (.a(a[103]),
	.b(b[103]),
	.c_in(temp[103]),
	.c_out(temp[104]),
	.s(sum[103]));
   FA_24 fa_i_104 (.a(a[104]),
	.b(b[104]),
	.c_in(temp[104]),
	.c_out(temp[105]),
	.s(sum[104]));
   FA_23 fa_i_105 (.a(a[105]),
	.b(b[105]),
	.c_in(temp[105]),
	.c_out(temp[106]),
	.s(sum[105]));
   FA_22 fa_i_106 (.a(a[106]),
	.b(b[106]),
	.c_in(temp[106]),
	.c_out(temp[107]),
	.s(sum[106]));
   FA_21 fa_i_107 (.a(a[107]),
	.b(b[107]),
	.c_in(temp[107]),
	.c_out(temp[108]),
	.s(sum[107]));
   FA_20 fa_i_108 (.a(a[108]),
	.b(b[108]),
	.c_in(temp[108]),
	.c_out(temp[109]),
	.s(sum[108]));
   FA_19 fa_i_109 (.a(a[109]),
	.b(b[109]),
	.c_in(temp[109]),
	.c_out(temp[110]),
	.s(sum[109]));
   FA_18 fa_i_110 (.a(a[110]),
	.b(b[110]),
	.c_in(temp[110]),
	.c_out(temp[111]),
	.s(sum[110]));
   FA_17 fa_i_111 (.a(a[111]),
	.b(b[111]),
	.c_in(temp[111]),
	.c_out(temp[112]),
	.s(sum[111]));
   FA_16 fa_i_112 (.a(a[112]),
	.b(b[112]),
	.c_in(temp[112]),
	.c_out(temp[113]),
	.s(sum[112]));
   FA_15 fa_i_113 (.a(a[113]),
	.b(b[113]),
	.c_in(temp[113]),
	.c_out(temp[114]),
	.s(sum[113]));
   FA_14 fa_i_114 (.a(a[114]),
	.b(b[114]),
	.c_in(temp[114]),
	.c_out(temp[115]),
	.s(sum[114]));
   FA_13 fa_i_115 (.a(a[115]),
	.b(b[115]),
	.c_in(temp[115]),
	.c_out(temp[116]),
	.s(sum[115]));
   FA_12 fa_i_116 (.a(a[116]),
	.b(b[116]),
	.c_in(temp[116]),
	.c_out(temp[117]),
	.s(sum[116]));
   FA_11 fa_i_117 (.a(a[117]),
	.b(b[117]),
	.c_in(temp[117]),
	.c_out(temp[118]),
	.s(sum[117]));
   FA_10 fa_i_118 (.a(a[118]),
	.b(b[118]),
	.c_in(temp[118]),
	.c_out(temp[119]),
	.s(sum[118]));
   FA_9 fa_i_119 (.a(a[119]),
	.b(b[119]),
	.c_in(temp[119]),
	.c_out(temp[120]),
	.s(sum[119]));
   FA_8 fa_i_120 (.a(a[120]),
	.b(b[120]),
	.c_in(temp[120]),
	.c_out(temp[121]),
	.s(sum[120]));
   FA_7 fa_i_121 (.a(a[121]),
	.b(b[121]),
	.c_in(temp[121]),
	.c_out(temp[122]),
	.s(sum[121]));
   FA_6 fa_i_122 (.a(a[122]),
	.b(b[122]),
	.c_in(temp[122]),
	.c_out(temp[123]),
	.s(sum[122]));
   FA_5 fa_i_123 (.a(a[123]),
	.b(b[123]),
	.c_in(temp[123]),
	.c_out(temp[124]),
	.s(sum[123]));
   FA_4 fa_i_124 (.a(a[124]),
	.b(b[124]),
	.c_in(temp[124]),
	.c_out(temp[125]),
	.s(sum[124]));
   FA_3 fa_i_125 (.a(a[125]),
	.b(b[125]),
	.c_in(temp[125]),
	.c_out(temp[126]),
	.s(sum[125]));
   FA_2 fa_i_126 (.a(a[126]),
	.b(b[126]),
	.c_in(temp[126]),
	.c_out(temp[127]),
	.s(sum[126]));
   FA_1 fa_i_127 (.a(a[127]),
	.b(b[127]),
	.c_in(temp[127]),
	.c_out(c_out),
	.s(sum[127]));
endmodule

